"""Changed Tournaments to Matches and added Tournaments table for managing tournaments

Revision ID: 0c1debbdb523
Revises: de66abe26187
Create Date: 2025-05-01 16:55:35.149606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1debbdb523'
down_revision = 'de66abe26187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('game_title', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_tournaments_game')
        batch_op.drop_index('ix_tournaments_points')
        batch_op.drop_index('ix_tournaments_result')
        batch_op.drop_index('ix_tournaments_time_taken')
        batch_op.drop_index('ix_tournaments_user_id')
        batch_op.create_index(batch_op.f('ix_tournaments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_game_title'), ['game_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('game')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('result')
        batch_op.drop_column('points')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('result', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('time_taken', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('game', sa.TEXT(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_game_title'))
        batch_op.drop_index(batch_op.f('ix_tournaments_date'))
        batch_op.create_index('ix_tournaments_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_tournaments_time_taken', ['time_taken'], unique=False)
        batch_op.create_index('ix_tournaments_result', ['result'], unique=False)
        batch_op.create_index('ix_tournaments_points', ['points'], unique=False)
        batch_op.create_index('ix_tournaments_game', ['game'], unique=False)
        batch_op.drop_column('date')
        batch_op.drop_column('game_title')
        batch_op.drop_column('name')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
