"""Adjusted Tournaments table to have a user_id attribute

Revision ID: 1a185a813ada
Revises: 880d94870c32
Create Date: 2025-05-11 11:47:18.132921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a185a813ada'
down_revision = '880d94870c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_user_id')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_tournaments_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournaments_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
