"""Initial migration

Revision ID: 4700f2bbe837
Revises: 
Create Date: 2025-05-10 10:45:50.988582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4700f2bbe837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('game_title', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('data_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_game_title'), ['game_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password'), ['password'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_private'), ['private'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_profile_picture'), ['profile_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Time(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='matches_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_time_taken'), ['time_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_matches_time_taken'))
        batch_op.drop_index(batch_op.f('ix_matches_result'))
        batch_op.drop_index(batch_op.f('ix_matches_points'))
        batch_op.drop_index(batch_op.f('ix_matches_game'))

    op.drop_table('matches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_profile_picture'))
        batch_op.drop_index(batch_op.f('ix_users_private'))
        batch_op.drop_index(batch_op.f('ix_users_password'))
        batch_op.drop_index(batch_op.f('ix_users_last_login'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_creation_date'))

    op.drop_table('users')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_game_title'))
        batch_op.drop_index(batch_op.f('ix_tournaments_date'))

    op.drop_table('tournaments')
    # ### end Alembic commands ###
