"""updated users

Revision ID: 518c88c18d5f
Revises: 5d3f9f639ef5
Create Date: 2025-04-24 12:45:57.776809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518c88c18d5f'
down_revision = '5d3f9f639ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password'), ['password'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_password'))
        batch_op.drop_index(batch_op.f('ix_users_last_login'))

    # ### end Alembic commands ###
