"""Recreated database to fix broken migrations

Revision ID: 56f705820311
Revises: ac1c030fc5b9
Create Date: 2025-05-03 15:50:01.008992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f705820311'
down_revision = 'ac1c030fc5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Time(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='matches_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_time_taken'), ['time_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user_id'), ['user_id'], unique=False)

    op.create_table('tournaments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('game_title', sa.Text(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_game_title'), ['game_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_game_title'))
        batch_op.drop_index(batch_op.f('ix_tournaments_date'))
    
    op.drop_table('tournaments')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_matches_time_taken'))
        batch_op.drop_index(batch_op.f('ix_matches_result'))
        batch_op.drop_index(batch_op.f('ix_matches_points'))
        batch_op.drop_index(batch_op.f('ix_matches_game'))

    op.drop_table('matches')
    # ### end Alembic commands ###
