"""empty message

Revision ID: 575e401bb8d2
Revises: 7406e470d526
Create Date: 2025-05-16 17:27:22.538928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575e401bb8d2'
down_revision = '7406e470d526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
