"""Added detail attribute to Tournaments table

Revision ID: 7406e470d526
Revises: 8ce13cf5e121
Create Date: 2025-05-12 15:23:49.769392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7406e470d526'
down_revision = '8ce13cf5e121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
