"""Renamed Data table to Tournaments

Revision ID: 8435c2ba72a1
Revises: fd559f87d67d
Create Date: 2025-04-27 21:04:20.585880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8435c2ba72a1'
down_revision = 'fd559f87d67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Time(), nullable=False),
    sa.Column('result', sa.Enum(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_time_taken'), ['time_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_index('ix_data_game')
        batch_op.drop_index('ix_data_points')
        batch_op.drop_index('ix_data_result')
        batch_op.drop_index('ix_data_time_taken')
        batch_op.drop_index('ix_data_user_id')

    op.drop_table('data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game', sa.TEXT(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.Column('time_taken', sa.TIME(), nullable=False),
    sa.Column('result', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.create_index('ix_data_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_data_time_taken', ['time_taken'], unique=False)
        batch_op.create_index('ix_data_result', ['result'], unique=False)
        batch_op.create_index('ix_data_points', ['points'], unique=False)
        batch_op.create_index('ix_data_game', ['game'], unique=False)

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_user_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_time_taken'))
        batch_op.drop_index(batch_op.f('ix_tournaments_result'))
        batch_op.drop_index(batch_op.f('ix_tournaments_points'))
        batch_op.drop_index(batch_op.f('ix_tournaments_game'))

    op.drop_table('tournaments')
    # ### end Alembic commands ###
