"""Added image attribute to Tournaments table

Revision ID: 880d94870c32
Revises: a823f3370236
Create Date: 2025-05-10 21:08:51.863546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880d94870c32'
down_revision = 'a823f3370236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_friends_to_user', 'users', ['to_user'], ['id'])
        batch_op.create_foreign_key('fk_friends_from_user', 'users', ['from_user'], ['id'])

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_file', sa.Text(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('data_file')
        batch_op.drop_column('image')

    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint('fk_friends_to_user', type_='foreignkey')
        batch_op.drop_constraint('fk_friends_from_user', type_='foreignkey')

    # ### end Alembic commands ###
