"""Merged the Tournaments and Matches tables

Revision ID: 8ce13cf5e121
Revises: 1a185a813ada
Create Date: 2025-05-11 21:16:00.723792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce13cf5e121'
down_revision = '1a185a813ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_game')
        batch_op.drop_index('ix_matches_points')
        batch_op.drop_index('ix_matches_result')
        batch_op.drop_index('ix_matches_time_taken')

    op.drop_table('matches')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tournaments_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_result'), ['result'], unique=False)
        batch_op.drop_column('data_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_file', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tournaments_time_taken'))
        batch_op.drop_index(batch_op.f('ix_tournaments_result'))
        batch_op.drop_index(batch_op.f('ix_tournaments_points'))
        batch_op.drop_column('result')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('points')

    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game', sa.TEXT(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.Column('time_taken', sa.TIME(), nullable=False),
    sa.Column('result', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='matches_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_time_taken', ['time_taken'], unique=False)
        batch_op.create_index('ix_matches_result', ['result'], unique=False)
        batch_op.create_index('ix_matches_points', ['points'], unique=False)
        batch_op.create_index('ix_matches_game', ['game'], unique=False)

    # ### end Alembic commands ###
