"""Added profile picture section to users table

Revision ID: ac1c030fc5b9
Revises: b41b7621e32c
Create Date: 2025-04-27 13:49:02.480722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1c030fc5b9'
down_revision = 'b41b7621e32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_profile_picture'), ['profile_picture'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_private'), ['private'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_profile_picture'))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
