"""Added email and creation_date field to users table

Revision ID: b41b7621e32c
Revises: 518c88c18d5f
Create Date: 2025-04-26 21:37:19.977160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41b7621e32c'
down_revision = '518c88c18d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_creation_date'))
        batch_op.drop_column('creation_date')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
