"""Added privacy attribute to users table

Revision ID: c0e381d7ddbf
Revises: 8c590e2f34b2
Create Date: 2025-05-01 11:48:39.297592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e381d7ddbf'
down_revision = '8c590e2f34b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_private'), ['private'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_private'))
        batch_op.drop_column('private')

    # ### end Alembic commands ###
