"""Added data table to database to store uploaded data

Revision ID: fd559f87d67d
Revises: b41b7621e32c
Create Date: 2025-04-27 16:53:57.011229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd559f87d67d'
down_revision = 'b41b7621e32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Time(), nullable=False),
    sa.Column('result', sa.Enum(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_time_taken'), ['time_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_data_time_taken'))
        batch_op.drop_index(batch_op.f('ix_data_result'))
        batch_op.drop_index(batch_op.f('ix_data_points'))
        batch_op.drop_index(batch_op.f('ix_data_game'))

    op.drop_table('data')
    # ### end Alembic commands ###
